### ISSUE TITLE
include working package-lock.json file

### ISSUE THREAD

**Issue by gregschroeder** [jessegrosjean/birch-outline#8]
as the package is a bit outdated, it no longer builds by default.  could you include or check in a package-lock.json file that references the working versions for all of the referenced dependencies?  obviously, updating the packages is preferred, but it would be easiest to start with a working version, and I'm hoping you just have one lying around that got .gitignore'd so it is low effort.

**Comment by dwertheimer** [comment]
@jessegrosjean I am trying to build this also...can't install the dependencies. Can you please help? I first had to update to Gulp4 to get past a tar error, but now stuck here:

`
~/D/P/t/b/birch-outline ❯❯❯ npm install
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> birch-outline@0.2.1 prepublish .../taskpaper-birch-outline/birch-outline/birch-outline
> ./node_modules/gulp/bin/gulp.js prepublish

[22:54:45] Failed to load external module coffeescript/register
[22:54:45] Requiring external module coffee-script/register
fs.js:39
} = primordials;
    ^
ReferenceError: primordials is not defined
    at fs.js:39:5
    at req_ (.../taskpaper-birch-outline/birch-outline/birch-outline/node_modules/natives/index.js:143:24)
`

**Comment by jessegrosjean** [comment]
Sorry for not responding sooner. I just tried a few quick fixes and failed to fix. I'd be happy to take a pull request, but don't have time to devote to this right now.
